/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsCreateRouteImport } from './routes/posts/create'
import { Route as AdminTagsCreateRouteImport } from './routes/admin/tags/create'
import { Route as AdminCategoriesCreateRouteImport } from './routes/admin/categories/create'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsCreateRoute = PostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsCreateRoute = AdminTagsCreateRouteImport.update({
  id: '/admin/tags/create',
  path: '/admin/tags/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesCreateRoute = AdminCategoriesCreateRouteImport.update({
  id: '/admin/categories/create',
  path: '/admin/categories/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/posts/create': typeof PostsCreateRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/tags/create': typeof AdminTagsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/posts/create': typeof PostsCreateRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/tags/create': typeof AdminTagsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/posts/create': typeof PostsCreateRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/tags/create': typeof AdminTagsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/posts/create'
    | '/admin/categories/create'
    | '/admin/tags/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/posts/create'
    | '/admin/categories/create'
    | '/admin/tags/create'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/posts/create'
    | '/admin/categories/create'
    | '/admin/tags/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PostsCreateRoute: typeof PostsCreateRoute
  AdminCategoriesCreateRoute: typeof AdminCategoriesCreateRoute
  AdminTagsCreateRoute: typeof AdminTagsCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/create': {
      id: '/posts/create'
      path: '/posts/create'
      fullPath: '/posts/create'
      preLoaderRoute: typeof PostsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags/create': {
      id: '/admin/tags/create'
      path: '/admin/tags/create'
      fullPath: '/admin/tags/create'
      preLoaderRoute: typeof AdminTagsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/create': {
      id: '/admin/categories/create'
      path: '/admin/categories/create'
      fullPath: '/admin/categories/create'
      preLoaderRoute: typeof AdminCategoriesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PostsCreateRoute: PostsCreateRoute,
  AdminCategoriesCreateRoute: AdminCategoriesCreateRoute,
  AdminTagsCreateRoute: AdminTagsCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
